[package]
name = "cadence-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
rodio = "0.17"
parking_lot = "0.12"
symphonia = { version = "0.5", features = ["flac", "mp3", "wav", "ogg"] }
serde = { version = "1.0", features = ["derive"] }
